# Generated by Django 4.2 on 2023-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
